/*
    8 Jan 2025
*/

const pictures = [
  {
    id: 1,
    uri: require("@/assets/pictures/1.jpg"),
    event: "CBCS Masters 2024 Finals",
    description: null,
    date: "Oct 2024",
    teams: ["RED Canids"],
    players: [`Marcelo 'coldzera' David`],
  },
  {
    id: 2,
    uri: require("@/assets/pictures/2.jpg"),
    event: "PGL CS2 Major Copenhagen 2024 Opening Stage",
    description: "Legacy vs FURIA",
    date: "17 Mar 2024",
    teams: ["FURIA", "Legacy"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Andrei 'arT' Piovezan`,
    ],
  },
  {
    id: 3,
    uri: require("@/assets/pictures/3.jpg"),
    event: "",
    description: null,
    date: "2019",
    teams: ["MIBR"],
    players: [`Marcelo 'coldzera' David`, `Gabriel 'FalleN' Toledo`],
  },
  {
    id: 4,
    uri: require("@/assets/pictures/4.jpg"),
    event: "PGL CS2 Major Copenhagen 2024 Americas RMR",
    description: null,
    date: "Mar 2024",
    teams: ["Legacy"],
    players: [`Marcelo 'coldzera' David`, `Eduardo 'dumau' Wolkmer`],
  },
  {
    id: 5,
    uri: require("@/assets/pictures/5.jpg"),
    event: "IEM Rio Major 2022",
    description: null,
    date: "Nov 2022",
    teams: ["Brazil"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
      `Lincoln 'fnx' Lau`,
    ],
  },
  {
    id: 6,
    uri: require("@/assets/pictures/6.jpg"),
    event: "IEM Rio Major 2022 Challengers Stage",
    description: null,
    date: "Oct/Nov 2022",
    teams: ["00NATION", "Imperial"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
    ],
  },
  {
    id: 7,
    uri: require("@/assets/pictures/7.jpg"),
    event: "PGL Major Antwerp 2022 Americas RMR",
    description: null,
    date: "Apr 2022",
    teams: ["00NATION", "Evil Geniuses"],
    players: [`Marcelo 'coldzera' David`, `Jake 'Stewie2K' Yip`],
  },
  {
    id: 8,
    uri: require("@/assets/pictures/8.jpg"),
    event: "IEM Road to Rio 2022 Americas RMR",
    description: null,
    date: "Oct 2022",
    teams: ["00NATION"],
    players: [`Marcelo 'coldzera' David`],
  },
  {
    id: 9,
    uri: require("@/assets/pictures/9.jpg"),
    event: "IEM Cologne 2022 Play-in",
    description: null,
    date: "Jul 2022",
    teams: ["00NATION"],
    players: [`Marcelo 'coldzera' David`],
  },
  {
    id: 10,
    uri: require("@/assets/pictures/10.jpg"),
    event: "IEM Katowice 2020",
    description: null,
    date: "Feb/Mar 2020",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`
    ],
  },
  {
    id: 11,
    uri: require("@/assets/pictures/11.jpg"),
    event: "IEM Katowice 2020",
    description: null,
    date: "Feb/Mar 2020",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,
      `Helvijs 'broky' Saukants`,
    ],
  },
  {
    id: 12,
    uri: require("@/assets/pictures/12.jpg"),
    event: "IEM Katowice 2020",
    description: null,
    date: "Feb/Mar 2020",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 13,
    uri: require("@/assets/pictures/13.jpg"),
    event: "IEM Katowice 2020",
    description: null,
    date: "Feb/Mar 2020",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Helvijs 'broky' Saukants`,
    ],
  },
  {
    id: 14,
    uri: require("@/assets/pictures/14.jpg"),
    event: "IEM Katowice 2020",
    description: null,
    date: "Feb/Mar 2020",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,
    ],
  },
  {
    id: 15,
    uri: require("@/assets/pictures/15.jpg"),
    event: "BLAST Pro Series Global Final 2019",
    description: null,
    date: "Dec 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,
      `Helvijs 'broky' Saukants`,
      `Olof 'olofmeister' Kajbjer`,
      `Håvard 'rain' Nygaard`,
    ],
  },
  {
    id: 16,
    uri: require("@/assets/pictures/16.jpg"),
    event: "ESL Pro League Season 10 Finals",
    description: null,
    date: "Dec 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Helvijs 'broky' Saukants`,
    ],
  },
  {
    id: 17,
    uri: require("@/assets/pictures/17.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,

    ],
  },
  {
    id: 18,
    uri: require("@/assets/pictures/18.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,

    ],
  },
  {
    id: 19,
    uri: require("@/assets/pictures/19.jpg"),
    event: "IEM Beijing 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,
    ],
  },
  {
    id: 20,
    uri: require("@/assets/pictures/20.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,
      `Helvijs 'broky' Saukants`,
      `Olof 'olofmeister' Kajbjer`,
      `Håvard 'rain' Nygaard`,
    ],
  },
  {
    id: 21,
    uri: require("@/assets/pictures/21.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,
      `Helvijs 'broky' Saukants`,
      `Olof 'olofmeister' Kajbjer`,
      `Håvard 'rain' Nygaard`,
    ],
  },
  {
    id: 22,
    uri: require("@/assets/pictures/22.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,
      `Helvijs 'broky' Saukants`,
      `Olof 'olofmeister' Kajbjer`,
      `Håvard 'rain' Nygaard`,
    ],
  },
  {
    id: 23,
    uri: require("@/assets/pictures/19.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
      `Nikola 'NiKo' Kovač`,
    ],
  },
  {
    id: 24,
    uri: require("@/assets/pictures/24.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 25,
    uri: require("@/assets/pictures/25.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Nikola 'NiKo' Kovač`,
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 26,
    uri: require("@/assets/pictures/26.jpg"),
    event: "BLAST Pro Series Copenhagen 2019",
    description: null,
    date: "Nov 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 27,
    uri: require("@/assets/pictures/27.jpg"),
    event: "ESL One New York 2019",
    description: null,
    date: "Sep 2019",
    teams: ["Faze Clan"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 28,
    uri: require("@/assets/pictures/28.jpg"),
    event: "ESL One Cologne 2019",
    description: null,
    date: "Jul 2019",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 29,
    uri: require("@/assets/pictures/29.jpg"),
    event: "ESL Pro League Season 9 Finals",
    description: null,
    date: "Jun 2019",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 30,
    uri: require("@/assets/pictures/30.jpg"),
    event: "ECS Season 7 Finals",
    description: null,
    date: "Jun 2019",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 31,
    uri: require("@/assets/pictures/31.jpg"),
    event: "IEM Sydney 2019",
    description: null,
    date: "Apr/May 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
    ],
  },
  {
    id: 32,
    uri: require("@/assets/pictures/32.jpg"),
    event: "IEM Sydney 2019",
    description: null,
    date: "Apr/May 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 33,
    uri: require("@/assets/pictures/33.jpg"),
    event: "IEM Sydney 2019",
    description: null,
    date: "Apr/May 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
      `João 'felps' Vasconcellos`
    ],
  },
  {
    id: 34,
    uri: require("@/assets/pictures/34.jpg"),
    event: "IEM Sydney 2019",
    description: null,
    date: "Apr/May 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
      `João 'felps' Vasconcellos`
    ],
  },
  {
    id: 35,
    uri: require("@/assets/pictures/35.jpg"),
    event: "BLAST Pro Series Miami 2019",
    description: null,
    date: "Apr 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
      `João 'felps' Vasconcellos`
    ],
  },
  {
    id: 36,
    uri: require("@/assets/pictures/36.jpg"),
    event: "BLAST Pro Series Miami 2019",
    description: null,
    date: "Apr 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
      `João 'felps' Vasconcellos`
    ],
  },
  {
    id: 37,
    uri: require("@/assets/pictures/37.jpg"),
    event: "BLAST Pro Series São Paulo 2019",
    description: null,
    date: "Mar 2019",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
    ],
  },
  {
    id: 38,
    uri: require("@/assets/pictures/38.jpg"),
    event: "BLAST Pro Series São Paulo 2019",
    description: null,
    date: "Mar 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
      `João 'felps' Vasconcellos`
    ],
  },
  {
    id: 39,
    uri: require("@/assets/pictures/39.jpg"),
    event: "WESG 2018 World Finals",
    description: null,
    date: "Mar 2019",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Epitacio 'TACO' de Melo`,
    ],
  },
  {
    id: 40,
    uri: require("@/assets/pictures/40.jpg"),
    event: "IEM Katowice 2019",
    description: null,
    date: "Feb/Mar 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
      `João 'felps' Vasconcellos`
    ],
  },
  {
    id: 41,
    uri: require("@/assets/pictures/41.jpg"),
    event: "IEM Katowice 2019",
    description: null,
    date: "Feb/Mar 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
      `Epitacio 'TACO' de Melo`,
      `João 'felps' Vasconcellos`
    ],
  },
  {
    id: 42,
    uri: require("@/assets/pictures/42.jpg"),
    event: "IEM Katowice 2019",
    description: null,
    date: "Feb/Mar 2019",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Nicolai 'device' Reedtz`,
      `Lukas 'gla1ve' Rossander`,
      `Peter 'dupreeh' Rasmussen`,
      `Danny 'zonic' Sørensen`,
    ],
  },
  {
    id: 43,
    uri: require("@/assets/pictures/43.jpg"),
    event: "Top 20 players of 2018",
    description: null,
    date: "Feb 2019",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 44,
    uri: require("@/assets/pictures/44.jpg"),
    event: "BLAST Pro Series Lisbon 2018",
    description: null,
    date: "Dec 2018",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Jake 'Stewie2K' Yip`,
    ],
  },
  {
    id: 45,
    uri: require("@/assets/pictures/45.jpg"),
    event: "ESL Pro League Season 8 Finals",
    description: null,
    date: "Dec 2018",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
      `Jake 'Stewie2K' Yip`,
      `Tarik 'tarik' Celik`,
    ],
  },
  {
    id: 46,
    uri: require("@/assets/pictures/46.jpg"),
    event: "BLAST Pro Series Copenhagen 2018",
    description: null,
    date: "Nov 2018",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`,
      `Tarik 'tarik' Celik`,
    ],
  },
  {
    id: 47,
    uri: require("@/assets/pictures/47.jpg"),
    event: "FACEIT Major 2018",
    description: null,
    date: "Sep 2018",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
      `Jake 'Stewie2K' Yip`,
      `Tarik 'tarik' Celik`,
    ],
  },
  {
    id: 48,
    uri: require("@/assets/pictures/48.jpg"),
    event: "FACEIT Major 2018",
    description: null,
    date: "Sep 2018",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
      `Jake 'Stewie2K' Yip`,
      `Tarik 'tarik' Celik`,
    ],
  },
  {
    id: 49,
    uri: require("@/assets/pictures/49.jpg"),
    event: "FACEIT Major 2018",
    description: null,
    date: "Sep 2018",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 50,
    uri: require("@/assets/pictures/50.jpg"),
    event: "ESL One Cologne 2018",
    description: null,
    date: "Jul 2018",
    teams: ["MIBR"],
    players: [
      `Marcelo 'coldzera' David`,
      `Jake 'Stewie2K' Yip`,
    ],
  },
  {
    id: 51,
    uri: require("@/assets/pictures/51.jpg"),
    event: "ESL One Belo Horizonte 2018",
    description: null,
    date: "Jun 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
      `Jake 'Stewie2K' Yip`,
      `Ricardo 'boltz' Prass`,
    ],
  },
  {
    id: 52,
    uri: require("@/assets/pictures/52.jpg"),
    event: "ESL One Belo Horizonte 2018",
    description: null,
    date: "Jun 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
      `Jake 'Stewie2K' Yip`,
      `Ricardo 'boltz' Prass`,
    ],
  },
  /*
  {
    id: 53,
    uri: require("@/assets/pictures/53.jpg"),
    event: "StarSeries i-League Season 5",
    description: null,
    date: "May/Jun 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
      `Jake 'Stewie2K' Yip`,
      `Ricardo 'boltz' Prass`,
    ],
  },
  {
    id: 54,
    uri: require("@/assets/pictures/54.jpg"),
    event: "StarSeries i-League Season 5",
    description: null,
    date: "May/Jun 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Jake 'Stewie2K' Yip`,
    ],
  },
  {
    id: 55,
    uri: require("@/assets/pictures/55.jpg"),
    event: "StarSeries i-League Season 5",
    description: null,
    date: "May/Jun 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
      `Jake 'Stewie2K' Yip`,
    ],
  },
  {
    id: 56,
    uri: require("@/assets/pictures/56.jpg"),
    event: "ELEAGUE Major 2018",
    description: null,
    date: "Jan 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 57,
    uri: require("@/assets/pictures/57.jpg"),
    event: "ELEAGUE Major 2018",
    description: null,
    date: "Jan 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Epitacio 'TACO' de Melo`,
      `João 'felps' Vasconcellos`,
      `Tyler 'Skadoodle' Latham`,
      `Jake 'Stewie2K' Yip`,
      `Tarik 'tarik' Celik`,
      `Timothy 'autimatic' Ta`,

    ],
  },
  {
    id: 58,
    uri: require("@/assets/pictures/58.jpg"),
    event: "ELEAGUE Major 2018",
    description: null,
    date: "Jan 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
    ],
  },
  {
    id: 59,
    uri: require("@/assets/pictures/59.jpg"),
    event: "ELEAGUE Major 2018",
    description: null,
    date: "Jan 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
      `Gabriel 'FalleN' Toledo`,
      `Fernando 'fer' Alvarenga`,
    ],
  },
  {
    id: 60,
    uri: require("@/assets/pictures/60.jpg"),
    event: "ELEAGUE Major 2018",
    description: null,
    date: "Jan 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 60,
    uri: require("@/assets/pictures/60.jpg"),
    event: "ELEAGUE Major 2018",
    description: null,
    date: "Jan 2018",
    teams: ["SK Gaming"],
    players: [
      `Marcelo 'coldzera' David`,
    ],
  },
  {
    id: 0,
    uri: require("@/assets/pictures/0.jpg"),
    event: "",
    description: null,
    date: "Jun 2019",
    teams: ["MIBR"],
    players: [
      `Gabriel 'FalleN' Toledo`,
      `Marcelo 'coldzera' David`,
      `Fernando 'fer' Alvarenga`
    ],
  },
  */
];

export default pictures;